apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  chart:
    spec:
      version: ">=17.11.0"
  values:
    architecture: standalone
    master:
      resources:
        limits:
          memory: 256Mi
          cpu: 250m
        requests:
          memory: 128Mi
          cpu: 100m
      persistence:
        size: 1Gi
    metrics:
      enabled: true
    # your staging-specific values here 